language: cpp
compiler: gcc
dist: xenial

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - libqt5core5a
            - libqt5gui5
            - libqt5network5
            - libqt5qml5
            - libqt5quick5
            - libqt5widgets5
            - libmariadbclient-dev
            - libevent-dev
            - libevent-openssl
            - libboost-program-options-dev
            - libssl-dev
            - libyaml-cpp-dev
            - pkg-config
            - libmagick++-dev
            - libargon2-dev

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
