language: cpp
compiler: gcc
dist: xenial

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - qtbase5-dev
            - qml-module-qtquick-controls
            - qml-module-qtquick2
            - qtdeclarative5-dev
            - libmysqlclient-dev
            - libevent-2.0.5
            - libboost-program-options-dev
            - libssl-dev
            - libyaml-cpp-dev
            - pkg-config
            - libmagick++-dev
r           - libcereal-dev

before_install:
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/argon2/libargon2-0_0~20161029-1.1_amd64.deb
    - sudo dpkg -i libargon2-0_0~20161029-1.1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/argon2/libargon2-0-dev_0~20161029-1.1_amd64.deb
    - sudo dpkg -i libargon2-0-dev_0~20161029-1.1_amd64.deb

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
