language: cpp
os: linux
dist: xenial

matrix:
    include:
        - compiler: gcc
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

        - compiler: clang
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-5.0
              packages:
                - clang-5.0
          env:
                - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - os: osx
          osx_image: xcode10.2
          compiler: clang
          env:
              - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./travis/travis_osx.sh; else ./travis/travis_linux.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.12.2; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2r; fi
    - eval "${MATRIX_EVAL}"

script:
    - cmake --version
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
