language: cpp
os: linux
dist: xenial

matrix:
    include:
        - compiler: gcc
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

        - compiler: clang
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-5.0
              packages:
                - clang-5.0
          env:
                - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - ./travis/travis_linux.sh
    - eval "${MATRIX_EVAL}"

script:
    - cmake --version
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
